api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
            extra_properties:
                standard_put: true
            normalization_context:
                skip_null_values: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    keep_legacy_inflector: false
    use_symfony_listeners: true
